source 'https://rubygems.org'

gem 'bundler'
gem 'sinatra'
gem 'compass'
gem 'haml'
gem 'zurb-foundation'
gem 'sinatra-partial'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-sqlite-adapter'
gem 'dm-timestamps'
gem 'dm-validations'
gem 'json'
gem 'rake'
gem 'sinatra-contrib'
